// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.898

package file_explorer

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func upload() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"file-upload-form\" hx-encoding=\"multipart/form-data\" hx-post=\"/api/v1/files/upload\" hx-swap=\"none\"><table><tbody><tr><td><input type=\"file\" name=\"file\" class=\"max-w-lg\"></td></tr><tr><td><button class=\"mr-4 mt-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg transition-colors duration-200 space-x-2\" hx-indicator=\"#file-upload-progress\">Upload</button> <progress id=\"file-upload-progress\" class=\"htmx-indicator \" value=\"0\" max=\"100\"></progress></td></tr></tbody></table><script>\n            htmx.on(\n                '#file-upload-form',\n                'htmx:xhr:progress',\n                function(evt) {\n                    htmx.find('#file-upload-progress').setAttribute(\n                        'value',\n                        evt.detail.loaded / evt.detail.total * 100,\n                    );\n                }\n            );\n        </script></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
